MyPersonalWebsite/Areas/Admin/Controllers/AuthorController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using MyPersonalWebsite.ClassLib.Data.Entities;
using MyPersonalWebsite.ClassLib.Models.Author;
using MyPersonalWebsite.ClassLib.Services.IServices;
using X.PagedList;

namespace MyPersonalWebsite.Areas.Admin.Controllers
{
    [Area("Admin")]
    [Authorize]
    public class AuthorController : Controller
    {
        private readonly IAuthorService _service;

        public AuthorController(IAuthorService service)
        {
            _service = service;
        }

        public async Task<IActionResult> Index(int? page)
        {
            IEnumerable<Author> authorList = await _service.GetAllAuthorsAsync();

            int pageSize = 10;
            int pageNumber = (page ?? 1);

            return View(authorList.ToPagedList(pageNumber, pageSize));
        }

        public IActionResult Create()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(AddAuthorModel author)
        {

            if (ModelState.IsValid)
            {
                await _service.AddAuthorAsync(author);

                return RedirectToAction("Index");
            }
            return View(author);
        }

        public async Task<IActionResult> EditAsync(int id)
        {
            if (id == null || id == 0)
            {
                return NotFound();
            }
            var authorFromDb = await _service.GetAuthorByIdAsync(id);

            if (authorFromDb == null)
            {
                return NotFound();
            }
            return View(authorFromDb);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(EditAuthorModel author)
        {

            if (ModelState.IsValid)
            {
                await _service.UpdateAuthorAsync(author);
                return RedirectToAction("Index");
            }

            return View(author);

        }

        public async Task<IActionResult> DeleteAsync(int id)
        {
            if (id == null || id == 0)
            {
                return NotFound();
            }

            var authorFromDb = await _service.GetAuthorDeleteByIdAsync(id);

            if (authorFromDb == null)
            {
                return NotFound();
            }
            return View(authorFromDb);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Delete(int id)
        {

            await _service.DeleteAuthorAsync(id);

            return RedirectToAction("Index");

        }
    }
}

MyPersonalWebsite/Controllers/BlogController.cs
using Microsoft.AspNetCore.Mvc;
using MyPersonalWebsite.ClassLib.Data;
using MyPersonalWebsite.ClassLib.Data.Entities;
using X.PagedList;
using MyPersonalWebsite.ClassLib.Models;
using MyPersonalWebsite.ClassLib.Services;
using MyPersonalWebsite.ClassLib.Services.IServices;

namespace MyPersonalWebsite.Controllers
{
    public class BlogController : Controller
    {
        private readonly IBlogUIService _service;

        public BlogController(IBlogUIService service)
        {
            _service = service;
        }

        public ViewResult Index(int? page)
        {
            IEnumerable<Blog> objBlogList = _service.GetAllBlogs();

            int pageSize = 3;
            int pageNumber = (page ?? 1);
            return View(objBlogList.ToPagedList(pageNumber, pageSize));
        }

        public IActionResult BlogDetail(int id)
        {
            Blog blogObj = _service.GetBlogById(id);

            return View(blogObj);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> AddComment(AddCommentModel addCommentModel)
        {
            if (ModelState.IsValid)
            {
                await _service.AddComment(addCommentModel);

                return RedirectToAction("BlogDetail", new { Id = addCommentModel.BlogId });
            }
            return View(addCommentModel);
        }
    }
}

MyPersonalWebsite/Controllers/NewsCategoryController.cs
using Microsoft.AspNetCore.Mvc;
using MyPersonalWebsite.ClassLib.Data.Entities;
using MyPersonalWebsite.ClassLib.Services.IServices;
using X.PagedList;

namespace MyPersonalWebsite.Controllers
{
    public class NewsCategoryController : Controller
    {
       private readonly INewsCategoryService _service;

        public NewsCategoryController(INewsCategoryService service)
        {
            _service = service;
        }
        public async Task<IActionResult> Index(int? page)
        {
            IEnumerable<NewsCategory> objNewsCategoryList = await _service.GetAllNewsCategories();

            int pageSize = 10;
            int pageNumber = (page ?? 1);

            return View(objNewsCategoryList.ToPagedList(pageNumber, pageSize));
        }

        public async Task<IActionResult> Details(int id, int? page)
        {
            var pageNumber = page ?? 1;   
            ViewData["news"] = await _service.GetNewsforCategory(id);

            return View();
        }

    }
}

MyPersonalWebsite/Controllers/NewsController.cs
using Microsoft.AspNetCore.Mvc;
using MyPersonalWebsite.ClassLib.Data.Entities;
using MyPersonalWebsite.ClassLib.Services.IServices;
using X.PagedList;

namespace MyPersonalWebsite.Controllers
{
    public class NewsController : Controller
    {
        private readonly INewsService _service;

        public NewsController(INewsService service)
        {
            _service = service;
        }
        public async Task<IActionResult> Index(int? page)
        {
            IEnumerable<News> objNewsList = await _service.GetAllNews();

            int pageSize = 10;
            int pageNumber = (page ?? 1);

            return View(objNewsList.ToPagedList(pageNumber, pageSize));
        }
    }
}

MyPersonalWebsite/Areas/Admin/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Admin</title>
    <link rel="stylesheet" href="~/css/bootswatchTheme.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/MyPersonalWebsite.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-lg navbar-light bg-light">
  <div class="container-fluid">
    <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">MyPersonalWebsite</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarColor03" aria-controls="navbarColor03" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarColor03">
      <ul class="navbar-nav me-auto">
        <li class="nav-item">
          <a class="nav-link text-dark" asp-area="Admin" asp-controller="Home" asp-action="Index">Admin Home</a>
        </li>
        <li class="nav-item">
          <a class="nav-link text-dark" asp-area="Admin" asp-controller="Blog" asp-action="Index">Admin Blog</a>
        </li>
         <li class="nav-item">
          <a class="nav-link text-dark" asp-area="Admin" asp-controller="Author" asp-action="Index">Authors</a>
        </li>
        <li class="nav-item">
          <a class="nav-link text-dark" asp-area="Admin" asp-controller="Category" asp-action="Index">Categories</a>
        </li>
        <li class="nav-item">
          <a class="nav-link text-dark" asp-area="Admin" asp-controller="News" asp-action="Index">News</a>
        </li>
        <li class="nav-item">
          <a class="nav-link text-dark" asp-area="Admin" asp-controller="NewsCategory" asp-action="Index">News Categories</a>
        </li>
      </ul>
       <partial name="_LoginPartial"/>
    </div>
  </div>

    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2022 - MyPersonalWebsite - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p" crossorigin="anonymous"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery-validate/1.19.3/jquery.validate.min.js" integrity="sha512-37T7leoNS06R80c8Ulq7cdCDU5MNQBwlYoy1TX/WUsLFC2eYNqtKlV0QjH7r8JpG/S0GUMZwebnVFLPd6SU5yg==" crossorigin="anonymous" referrerpolicy="no-referrer"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery-validation-unobtrusive/3.2.12/jquery.validate.unobtrusive.min.js" integrity="sha512-o6XqxgrUsKmchwy9G5VRNWSSxTS4Urr4loO6/0hYdpWmFUfHqGzawGxeQGMDqYzxjY9sbktPbNlkIQJWagVZQg==" crossorigin="anonymous" referrerpolicy="no-referrer"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>