MyPersonalWebsite/Areas/Admin/Controllers/CategoryController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using MyPersonalWebsite.ClassLib.Data.Entities;
using MyPersonalWebsite.ClassLib.Models.Category;
using MyPersonalWebsite.ClassLib.Services.IServices;
using X.PagedList;

namespace MyPersonalWebsite.Areas.Admin.Controllers
{
    [Area("Admin")]
    [Authorize]
    public class CategoryController : Controller
    {
        private readonly ICategoryService _service;

        public CategoryController(ICategoryService service)
        {
            _service = service;
        }
        public async Task<IActionResult> Index(int? page)
        {
            IEnumerable<Category> categoryList = await _service.GetAllCategoriesAsync();

            int pageSize = 10;
            int pageNumber = (page ?? 1);

            return View(categoryList.ToPagedList(pageNumber, pageSize));
        }

        public IActionResult Create()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(AddCategoryModel category)
        {
            if (ModelState.IsValid)
            {
                await _service.AddCategoryAsync(category);

                return RedirectToAction("Index");
            }
            return View(category);
        }

        public async Task<IActionResult> EditAsync(int id)
        {
            if (id == null || id == 0)
            {
                return NotFound();
            }
            var categoryFromDb = await _service.GetCategoryByIdAsync(id);

            if (categoryFromDb == null)
            {
                return NotFound();
            }
            return View(categoryFromDb);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(EditCategoryModel category)
        {

            if (ModelState.IsValid)
            {
                await _service.UpdateCategoryAsync(category);
                return RedirectToAction("Index");
            }

            return View(category);

        }

        public async Task<IActionResult> DeleteAsync(int id)
        {
            if (id == null || id == 0)
            {
                return NotFound();
            }

            var categoryFromDb = await _service.GetCategoryDeleteByIdAsync(id);

            if (categoryFromDb == null)
            {
                return NotFound();
            }
            return View(categoryFromDb);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Delete(int id)
        {

            await _service.DeleteCategoryAsync(id);

            return RedirectToAction("Index");

        }

    }
}

MyPersonalWebsite/Areas/Admin/Views/Category/Create.cshtml
@using MyPersonalWebsite.ClassLib.Models.Category
@model AddCategoryModel

<form method="post" asp-action="Create">
    <div>
        <div>
            <h2 class="text-primary">New Category</h2>
            <hr/>
        </div>

        <div>
            <label asp-for="Name"></label>
            <input asp-for="Name" class="form-control" />
            <span asp-validation-for="Name" class="text-danger"></span>
        </div>

        <br/>

        <button type="submit" class="btn btn-primary" style="width:150px">Add</button>
        <a asp-controller="Category" asp-action="Index" class="btn btn-secondary">
            Back to List
        </a>

   </div>
 </form>

MyPersonalWebsite/Areas/Admin/Views/Category/Delete.cshtml
@using MyPersonalWebsite.ClassLib.Data.Entities
@model Category

<form method="post" asp-action="Delete">
    <input asp-for="Id" hidden />
    <div>
        <div>
            <h2 class="text-primary">Delete Category</h2>
            <hr/>
        </div>
        <div asp-validation-summary="All"></div>
        <div>
            <label asp-for="CategoryName"></label>
            <input asp-for="CategoryName" class="form-control" />
            <span asp-validation-for="CategoryName" disabled class="text-danger"></span>
        </div>

        <br />
        <button type="submit" class="btn btn-danger" style="width:150px">Delete</button>
        <a asp-controller="Category" asp-action="Index" class="btn btn-secondary" style="width:150px">
            Back to List
        </a>
        

    </div>



</form>

MyPersonalWebsite/Areas/Admin/Views/Category/Edit.cshtml
@using MyPersonalWebsite.ClassLib.Models.Category
@model EditCategoryModel

<form method="post" asp-action="Edit">
    <input asp-for="Id" type="hidden" />
    <div>
        <div>
            <h2 class="text-primary">Edit Category</h2>
            <hr />

            <label asp-for="Name"></label>
            <input asp-for="Name" class="form-control" />
            <span asp-validation-for="Name" class="text-danger"></span>
        </div>
       
    <button type="submit" class="btn btn-primary mt-1" style="width:150px">Update</button>
    <a asp-controller="Category" asp-action="Index" class="btn btn-secondary" style="width:150px">
        Back to List
    </a>

    </div>
    </div>

</form>

MyPersonalWebsite/Areas/Admin/Views/Category/Index.cshtml
@model X.PagedList.IPagedList<MyPersonalWebsite.ClassLib.Data.Entities.Category>
@using X.PagedList;
@using X.PagedList.Mvc.Core;
    
<link href="~/Content/PagedList.css" rel="stylesheet" 
  type="text/css" />

<h1 class="text-primary">List of Categories</h1>
  <hr />

    <div class= col-12>
    <a asp-controller="Category" asp-action="Create" class="btn btn-outline-primary">New Category</a>
    </div>

  <br/>

  <div class="container">
    @foreach (var obj in Model){
  <div class="row">
     <div class="col-6">
      <label>Category Name:</label>
      @obj.CategoryName
      </div>
  </div>

    <br/>

  <a asp-controller="Category" asp-action="Edit" asp-route-id="@obj.Id" class="btn btn-outline-warning"> Edit</a>
  <a asp-controller="Category" asp-action="Delete" asp-route-id="@obj.Id" class="btn btn-outline-danger"> Delete</a>
<hr />
    }
</div>