MyPersonalWebsite/Areas/Admin/Controllers/TagController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using MyPersonalWebsite.ClassLib.Data.Entities;
using MyPersonalWebsite.ClassLib.Models;
using MyPersonalWebsite.ClassLib.Services.IServices;
using System.Linq;

namespace MyPersonalWebsite.Areas.Admin.Controllers
{
    [Area("Admin")]
    [Authorize]
    public class TagController : Controller
    {
        private readonly IBlogTagService _service;

        public TagController(IBlogTagService service)
        {
            _service = service;
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> AddTag(AddTagModel addTagModel)
        {
            if (ModelState.IsValid)
            {
                await _service.AddTag(addTagModel);

                return RedirectToAction("Edit", "Blog", new { Id = addTagModel.BlogsId });
            }
            return View(addTagModel);
        }

        [HttpGet]
        public async Task<IActionResult> DeleteTag(DeleteTagModel model)
        {
            return View(await _service.GetDeleteModel(model));
        }

        [HttpPost, ActionName("DeleteTag")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteTag_POST(DeleteTagModel deleteTagModel)
        {
            await _service.DeleteTag(deleteTagModel);

            return RedirectToAction("Edit", "Blog", new { Id = deleteTagModel.BlogId });
        }
    }
}

MyPersonalWebsite/Areas/Admin/Views/Tag/DeleteTag.cshtml
@using MyPersonalWebsite.ClassLib.Models
@model DeleteTagModel

<div class="alert alert-danger">
    @Model.Description
</div>

<form method="post" asp-action="DeleteTag" asp-controller="Tag">
    <input type="hidden" asp-for="BlogId"/>
    <input type="hidden" asp-for="TagId" /> 

    <button type="submit" class="btn  btn-outline-danger">Confirm Delete</button>
</form>